;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        coffee-dedent-line-backspace
        dabbrev-expand
        indent-for-tab-command
        kill-rectangle
        left-subword
        maybe-delete-selection-and-yank
        pad-colon
        right-subword
        ruby-end-space
        sgml-close-tag
        slim-electric-backspace
        smart-tab
        tab-dwim
        yaml-electric-dash-and-dot
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        align-regexp
        beginning-of-buffer
        end-of-buffer
        goto-line-with-feedback
        ido-find-file
        next-error
        persp-switch
        query-replace
        smex
        sp--self-insert-command
        ))
