;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        dabbrev-expand
        indent-for-tab-command
        maybe-delete-selection-and-yank
        ruby-end-space
        smart-tab
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        ))
